apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhttpdtst
  labels:
    app: httpdtst
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpdtst
  template:
    metadata:
      name: httpdtst
      labels:
        app: httpdtst
    spec:
      containers:
        - name: httpdtst
          image: rabita13/rabitanginx03:1.0
          ports:
          - containerPort: 80